services:

  mongo-test:
    image: mongo:8
    container_name: spacex_mongodb_test
    ports:
      - "37017:27017"
    volumes:
      - spacex_mongo_test_data:/data/db  
    networks:
      - gateway-test

  redis-test:
    image: redis:7.2-alpine
    container_name: spacex_redis_test
    ports:
      - "36379:6379"
    volumes:
      - spacex_redis_test_data:/data 
    networks:
      - gateway-test

  rabbit-test:
    image: rabbitmq:4-management-alpine
    container_name: spacex_rabbitmq_test
    ports:
      - "35672:5672"
      - "35673:15672"
    volumes:
      - spacex_rabbitmq_test_data:/var/lib/rabbitmq  
    networks:
      - gateway-test

volumes:
  spacex_mongo_test_data:
  spacex_redis_test_data:
  spacex_rabbitmq_test_data:

networks:
  gateway-test: