export const GatewayEvents = {
    LAUNCH_RECEIVED: 'LAUNCH_RECEIVED',
    ENRICH_LAUNCHED: 'ENRICH_LAUNCHED',
    ROCKETS_LOADED: 'ROCKETS_LOADED',
    SHIPS_LOADED: 'SHIPS_LOADED',
    PAYLOADS_LOADED: 'PAYLOADS_LOADED',
    OTHER_EVENT: 'OTHER_EVENT',
} as const;